export const studentInitialValues = {
  apellido: "",
  nombre: "",
  dni: "",
  mail: "",
  celular: "",
  ciudad: "",
  tutores: "",
  relPrograma: "",
  añoIngreso: "",
  cuatIngreso: "",
  trabaja: false,
  relCarrera: false,
  horarioTrabajo: "",
  detallesTrabajo: "",
  plan: "",
}