export const studentInitialValues = {
  apellido: "",
  nombre: "",
  dni: "",
  mail: "",
  celular: "",
  ciudad: "",
  cursando: false,
  tutores: [],
  trabaja: false,
  relCarrera: false,
  horarioTrabajo: "",
  detallesTrabajo: "",
  plan: "",
}